### ISSUE TITLE
skip downloading model weights

### ISSUE THREAD

**Issue by sieste** [cocktailpeanut/dalai#1]
I have already downloaded the 7B model weights. How can I avoid redownloading them with `npx dalai llama`?

**Comment by marcuswestin** [comment]
Fixed in #16

**Comment by ekp1k80** [comment]
You have these 2 options
https://github.com/cocktailpeanut/dalai/pull/16
https://github.com/cocktailpeanut/dalai/pull/5

I recomment the 16. I download the repo and **run yarn just:run** You have to move the models folder (the model you already download) to llama.cpp

I did'nt be able to run it so. The file convert-pth-to-ggml.py is crashing in the line 
    model = torch.load(fname_model, map_location="cpu")
I think is because i don't have enought ram but i saw (in others repositories on twitter) a dude runned it in an raspberry pi
So... something is not working correctly

**Comment by marcuswestin** [comment]
Hey @cocktailpeanut if you'd like help managing issues etc I'm happy to help out.

(E.g this one has been fixed and I can mark it if I have permission)
