### ISSUE TITLE
Torrents are illegal in Germany

### ISSUE THREAD

**Issue by dliubarskyi** [cocktailpeanut/dalai#324]
Hi,

firs of all, thank you for your work!

I was installing alpaca on my PC and was not aware that there is torrenting involved.
The problem is, it is illegal to use torrents in Germany and it is fined with 1000+ USD/EUR.
Could you please include some **warning** in the documentation that there is a torrenting involved?
Thank you!

**Comment by amosayomide05** [comment]
Edit `readme.md` stating it and create a pull request, I am sure he will merge it 🙃

**Comment by ramzeez88** [comment]
@ljubarskij You can dowload the model from hugginface

**Comment by dliubarskyi** [comment]
@ramzeez88 could you please give more info on how to do that and which exactly model to use? Thanks!

**Comment by ramzeez88** [comment]
https://huggingface.co/Pi3141/alpaca-7B-ggml/resolve/main/ggml-model-q4_0.bin
you can dowload the alpaca model from there.

**Comment by clusterzx** [comment]
What a nonsense. Torrents are not illegal in Germany unless you are downloading/distributing illegal or copyrighted files. @ljubarskij

**Comment by dliubarskyi** [comment]
@ramzeez88 thank you!

**Comment by flexchar** [comment]
This is indeed a misleading statement. I'd like to clarify. The torrents are like highway, i.e. the way to share information. So it is equivalent to say that using internet, or paying by cash is illegal. Now the confusion comes because torrents are super efficient to share large files such as movies (which typically are copyrighted content) and as such, breaking copyright law, aka pirating is illegal. Hope that clarifies! 
 
Using torrents is much faster and more environmental friendly.
