### ISSUE TITLE
Getting a "(index):188 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')"

### ISSUE THREAD

**Issue by coryking** [cocktailpeanut/dalai#34]
When I type a prompt and hit enter, I do not get a response. Google's console is returning this:

![2023-03-13_22-52-48](https://user-images.githubusercontent.com/526250/224908824-098b9e59-9045-4557-9c17-7f98a947a12b.png)

Here is what is happening on the command line:

![2023-03-13_22-53-21](https://user-images.githubusercontent.com/526250/224908909-8fe0292f-00e6-4c0c-aa6a-c63308a407d5.png)

It looks like it is getting responses back from the websocket though:

![2023-03-13_22-55-58](https://user-images.githubusercontent.com/526250/224909177-695cced7-7d0b-4e92-a7d2-485095093c7a.png)

Note I am not hitting this by localhost, but via an IP address on my local network.

**Comment by xaverhimmelsbach** [comment]
This is because window.crypto.subtle is disabled in insecure contexts. Accessing an IP over plain HTTP counts as insecure, see [https://stackoverflow.com/questions/46468104/how-to-use-subtlecrypto-in-chrome-window-crypto-subtle-is-undefined](https://stackoverflow.com/questions/46468104/how-to-use-subtlecrypto-in-chrome-window-crypto-subtle-is-undefined).

The proper fix would be to enable HTTPS on the server and assign a domain, but for testing I created a port forwarding from port 3000 on my local machine to port 3000 on my server and accessed Dalai over localhost:3000. This worked, as localhost counts as a secure context and thus window.crypto.subtle is defined.

**Comment by coryking** [comment]
Can confirm this is the problem. Once I set up SSH port forwarding and connected via "localhost", everything worked.

I'll close this out.
